### ISSUE TITLE
Add a nice contributing file for anybody who wants to contribute to the project

### ISSUE THREAD

**Issue by quilesbaker** [Code-for-Miami/restaurant-inspections-api#11]

**Comment by leordev** [comment]
@ErnieAtLYD do we have any CFM default standards to contributing policy?

**Comment by ErnieAtLYD** [comment]
@leordev Not a standard, but here are three from Code for America I think work. Take a look at them and adapt it to what works for you! 

- https://github.com/codeforamerica/ohana-api/blob/master/CONTRIBUTING.md
- https://github.com/codeforamerica/streetmix/blob/master/CONTRIBUTING.md

**Comment by leordev** [comment]
Done here: https://github.com/Code-for-Miami/restaurant-inspections-api/blob/master/CONTRIBUTING.md
