### ISSUE TITLE
Compojure-api with Swagger for API Docs instead of Wiki

### ISSUE THREAD

**Issue by leordev** [Code-for-Miami/restaurant-inspections-api#13]

**Comment by ErnieAtLYD** [comment]
Another option for documentation can be this: https://github.com/lord/slate/
In theory, we would just install slate as a `gh-pages` branch and then if the API URL doesn't have arguments it can redirect to an URL.

That said, I'll let you choose what you'd want to go with!

**Comment by leordev** [comment]
Nice @ErnieAtLYD ! Actually we can generate automatically the Swagger APIs through compojure and then distribute and proide our API using the beauty Slate! 

Further info here: http://stackoverflow.com/questions/29469938/slate-vs-swagger-which-is-better-and-which-have-more-options

**Comment by ErnieAtLYD** [comment]
Ah-ha! Good to know, I'll add an additional issue then.
