### ISSUE TITLE
make startDate and endDate optional fields rather than required

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/restaurant-inspections-api#16]
To do that, we'd have to decide on the following:

- [ ] Decide on what the default endDate would be. I suggest the current date.
- [ ] Decide on what the default startDate would be. You have 10 days; whatever you think works the best!

- [ ] What happens if either endDate or startDate has an invalid value? Does the API fail gracefully?

**Comment by leordev** [comment]
We did not forget about that. Just depending on standardizing the whole API on #5.

**Comment by quilesbaker** [comment]
Part of #5 as well. (Duplicate)
