### ISSUE TITLE
Documentation: include instructions on how someone can install this on their own system

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/restaurant-inspections-api#2]
An example of how some github repos have documented their install process can be seen here: https://github.com/codeforamerica/howto

**Comment by ErnieAtLYD** [comment]
Nice job!
https://github.com/Code-for-Miami/restaurant-inspections-api/wiki/How-to-Install%3F

**Comment by leordev** [comment]
Thank you! Closing in 3, 2, 1... 💃
