### ISSUE TITLE
Hide user/password info in start

### ISSUE THREAD

**Issue by marcoslhc** [Code-for-Miami/restaurant-inspections-api#29]
If I do
```sh
export DATABASE_URL="jdbc:mysql://localhost:3306/codeformia_restaurant_inspections?user=myuser&password=mypassword"
```

executing `./start.sh` will log:
```
ago 14, 2016 6:49:53 P.M. clojure.tools.logging$eval1$fn__5 invoke
INFORMACIÓN: Environment variable DATABASE_URL detected:  jdbc:mysql://localhost:3306/codeformia_restaurant_inspections?user=myuser&password=mypassword
```
Giving sensitive information about the database. Not a concern using local but definitely a concern with CI services that shows logs.

**Comment by leordev** [comment]
Nice point!

I fixed this to not show the DATABASE_URL if PRODUCTION mode is enabled and the DATABASE_URL is not the default one here: https://github.com/Code-for-Miami/restaurant-inspections-api/commit/d3e8f4f6ff9843a994ceae258c3912caf9e485a9#diff-f0c56d2f5e5c3189bc6d49db68b581beR38
