### ISSUE TITLE
To do: migrate from developer's personal DO account to Code for Miami paid DO account

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/restaurant-inspections-api#3]

**Comment by leordev** [comment]
Please let me know if you need any help during this process.
If you provide me access I can do the migration by myself, though if anyone else does that we can assure that our wiki install instructions are ok.

**Comment by CyberStrike** [comment]
@ErnieAtLYD @leordev I Could put this on our heroku. The only issue would be that we have to swap to the DB to Postgresql.

**Comment by leordev** [comment]
Awesome Chris! I think it's not big deal... The problem is that right now we have 550k+ rows and increasing everyday... Can you support this data?

**Comment by CyberStrike** [comment]
@leordev ....that's a lot of data. I don't think we can put that much on to our heroku it would be at $50 a month for that much. Where are we getting that much data from historical?

**Comment by leordev** [comment]
@CyberStrike hahah yes that's what I'm talking about... it's too much. So, yeah, I think the best option is remains on DigitalOcean. Right now it's on my account, which I will always keep... But if you want to move for any "official" Code-For-Miami it's ok for me. What you can do also is to get a subdomain under codefor.miami and then I can provide the server in that address instead of using my digital ocean machine IP.

**Comment by ErnieAtLYD** [comment]
So I do have a DigitalOcean account as well, used for Councilmatic.

@leordev, when you're ready to migrate, let me know. Maybe a week or two before you have to return to Brazil (we'll miss you :( )

**Comment by leordev** [comment]
@ErnieAtLYD hey buddy please don't kick me out!!! it's gonna take a long time, my wife is just starting her college hahaha....

But anyway, yes I can keep in my DO forever if you want, because I have some personal works there! Don't worry.

You can close this issue for now if you want ;)

**Comment by ErnieAtLYD** [comment]
Closing the issue because I thought @leordev was returning to Brazil. He's staying in Miami! FOREVER! ;)
