### ISSUE TITLE
Environmental vars might be set on build, not on run. Audit this.

### ISSUE THREAD

**Issue by teh0xqb** [Code-for-Miami/restaurant-inspections-api#43]
Setup app with env vars. Build. Push to a different environment server. Run and check env vars. Are they the env vars or the build env, or of the running env?

This might have been introduced in an attempt to log these env vars only once. Used to be the case the these were logged when defined to build, when testing, when starting server, and upon responding to requests- which resulted in a lot of noise in logs.

**Comment by quilesbaker** [comment]
Reproduced. need to remove ^:const in constants.clj

**Comment by teh0xqb** [comment]
merged directly to master. removed ^:const.
