### ISSUE TITLE
Update readme/docs/repo API link to newest instance

### ISSUE THREAD

**Issue by teh0xqb** [Code-for-Miami/restaurant-inspections-api#45]

**Comment by quilesbaker** [comment]
Also setup nginx to expose running service.

**Comment by teh0xqb** [comment]
I destroyed my instance and I don't have the access right for leo's. I wonder if Code for Miami has instances available. If not, I'll create a new instance for myself again.

**Comment by teh0xqb** [comment]
running my own instance. updated readme and wiki
