### ISSUE TITLE
Follow 18F API best practices

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/restaurant-inspections-api#5]
18F which is the technology team inside the US federal government has built an API best practices and standards document. Think it's a good idea to follow as much as we can: https://github.com/18f/api-standards

As I see good ideas from the document I'll be adding more issues as we go along!

**Comment by leordev** [comment]
@ErnieAtLYD what do you think about jsonapi.org ?

**Comment by ErnieAtLYD** [comment]
Also @leordev that's the first time I've seen this jsonapi.org site; I'm open to it. Very cool!

**Comment by quilesbaker** [comment]
jsonapi.org turned out to be too complicated. Assigned this one to myself: implementing 18F and startDate/endDate optional

**Comment by quilesbaker** [comment]
Will take care of using optional dates. Also will handle incorrect date format.

**Comment by quilesbaker** [comment]
PR #33 Will take care of this one. Still a work in progress. Hopefully it makes everyone happy.
