### ISSUE TITLE
Who is paying for http://45.55.191.140 nowadays?

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/restaurant-inspections-api#52]
Hi @leordev - are you still paying for the Digital Ocean droplet? We'd love to still have you at the Brigade meetings of course but if you can't make it we understand; if that's the case, would you want us to start paying for these going forward?

**Comment by teh0xqb** [comment]
@ErnieAtLYD I'm the gatekeeper now!

![gatekeeper](http://vignette4.wikia.nocookie.net/ghostbusters/images/9/92/GB1film1999chapter26sc033.png/revision/latest?cb=20140604042016)

**Comment by teh0xqb** [comment]
The API is hosted on my instance. I was wondering how CFM dealt with these. We can discuss here or in slack.

**Comment by CyberStrike** [comment]
We have a heroku account being handled by rebekah and ernie I think. 
Our two options are to get a digitalocean account or convert this to heroku.

**Comment by ErnieAtLYD** [comment]
We currently do pay for a DigitalOcean account for Councilmatic, but I may
be dropping that soon due to developer inactivity. Now that we're on a
budget, I'm just paying for it with the Mangrove Labs account and making ML
a sponsor of open hack night.

Chris, may be a good idea to start a document on what to do re: hosting
your own code.

**Comment by CyberStrike** [comment]
@ErnieAtLYD "Hosting: Your Own Code" or "How to host your Code for Miami Project"?

**Comment by ErnieAtLYD** [comment]
Either works. Let's do the latter.

If the doc is about hosting a CFM project then don't forget to include the
HTML only options like Github pages via Jekyll.

**Comment by ErnieAtLYD** [comment]
It's under my account now. DADDY WARBUCKS, Y'ALL
