### ISSUE TITLE
Add schema updates to businesses enspoint

### ISSUE THREAD

**Issue by marcoslhc** [Code-for-Miami/restaurant-inspections-api#62]
There were some changes in https://github.com/Code-for-Miami/restaurant-inspections-api/pull/61 that needs an update in swagger

**Comment by teh0xqb** [comment]
Oh.. you want to take care of that as a diff PR? I'd argue that each time that we modify the API we should modify that swagger object with it. Its such a simple change, and new issues can be forgotten.

**Comment by marcoslhc** [comment]
Thats ok. Just remember to closed after #61 is merged
