### ISSUE TITLE
Standarize json output keys format

### ISSUE THREAD

**Issue by teh0xqb** [Code-for-Miami/restaurant-inspections-api#76]
/businesses uses underscores _, inspections uses camelCase, counties don't use any (countyname)

ugh Open Source :(

**Comment by teh0xqb** [comment]
@marcoslhc this sounds interesting huh? ^ :/

**Comment by teh0xqb** [comment]
We can use

```
(defn transform-keys
  "Recursively transforms all map keys in coll with the transform-key fn."
  [transform-key coll]
  (letfn [(transform [x] (if (map? x)
                           (into {} (map (fn [[k v]] [(transform-key k) v]) x))
                           x))]
    (walk/postwalk transform coll)))
```

and a transform-key function that uses regex to replace some_thing to some-thing for all endpoints.

**Comment by marcoslhc** [comment]
LOL. I guess we should keep a standars page in the wiki and start refactoring

**Comment by teh0xqb** [comment]
We'll use underscores for now. Just merged a PR for this. This is what the db/model uses and is simpler. We can reopen if we want to reformat all to camelCase.
