### ISSUE TITLE
Simplify application startup

### ISSUE THREAD

**Issue by quilesbaker** [Code-for-Miami/restaurant-inspections-api#9]
There's multiple things to consider here:

- [x] Adding :aot and :main to project.clj will make the command to run easier to run (don't have to specify the class path nor main class).

- [x] Maybe a short bash script that does the whole thing, instead of telling the user to run commands to compile. It would also pass the environmental variables to run, etc.

- As an overkill, create a simple docker instance that boots up with mysql and runs the server in a container. FOR LATER.

**Comment by leordev** [comment]
Cool! I totally agree with all of your points!
